[package]
name = "dpm"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8.22"
clap = { version = "4.5.38", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
chrono = "0.4.41"

[profile.release]
strip = true